### ISSUE TITLE
Update Keycloak to 20, timeboxed 1 day

### ISSUE THREAD

**Issue by rti** [dot-base/keycloak#48]

**Comment by defo10** [comment]
While you are updating keycloak, would you mind switching to a mirror which supports arm architectures out of the box? Keycloak is officially released on [quay.io](https://quay.io/repository/keycloak/keycloak), where the builds are also shipped with a corresponding arm image.
Changing the mirror to quay.io should be as simple as changing `FROM jboss/keycloak:<tag>` in the dockerfile to `FROM quay.io/keycloak/keycloak:<tag>`

**Comment by mecklenburg** [comment]
this is now referenced in #64
