### ISSUE TITLE
Update Keycloack to 21.1 

### ISSUE THREAD

**Issue by Zbozi** [dot-base/keycloak#64]
### 🚀 Feature Description
Update keycloak to version 21.1.2, which is the latest 21.x version

### ✔ Goals / ToDo
The following changes and things need to be taken care of, when updating to 21.xxx
- [x] Explicitly define `\auth`
- [x] One time password, custom provider integration
- [x] Update paramter in environment:  `KEYCLOAK_USER` ,`KEYCLOAK_PASSWORD` to `KEYCLOAK_ADMIN`, `KEYCLOAK_ADMIN_PASSWORD`
- [x] [Importing](https://www.keycloak.org/server/importExport) realms at startup
- [x] Integrate in deployment pipeline
- [x] ~~User migration~~ Luckily not needed!
- [x] ~~Update Realm automation~~ Will be handled in a separate issue

#### Research
- [x] Changes in [storage](https://www.keycloak.org/docs/latest/release_notes/index.html#changes-in-keycloak-storage), check legacy store cause it moves to a separate module called keycloak-model-legacy, " This change impacts several areas, especially areas related to user federation and custom user providers.
- [x] Monitoring now with [micrometer](https://www.keycloak.org/docs/latest/release_notes/index.html#keycloak-uses-micrometer-for-metrics)

### 🧰 Possible Solution
- https://quay.io/repository/keycloak/keycloak?tab=tags&tag=latest
- https://github.com/dot-base/deployments/issues/112
- https://www.keycloak.org/server/importExport
- https://www.youtube.com/watch?v=tQ2KmCqW9m8

**Comment by mecklenburg** [comment]
Lets split this into three issues:
1. Update with endpoints
2. Migrate realm config into new version & Include into automatic deployment pipeline
3. Data migration necessary?
