### ISSUE TITLE
Login not possible due to HTTP 403 on /userinfo endpoint with keycloak 21.1

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/keycloak#70]
### 🚀 Feature Description
Log in does not work with the keycloak upgrade due to changed config requirements. 
Log into keycloak admin console and add the following in both realms - `patients` and `dotbase`:
1) In keycloak admin console **create new client scope** `openid`
<img width="1160" alt="Bildschirmfoto 2023-08-16 um 16 42 31" src="https://github.com/dot-base/keycloak/assets/38720222/7fd45b44-de4b-427a-a3f4-7960a4e07ef7">

2) **Assign this scope** to the client `authentication-gateway` as a `default`

<img width="1402" alt="Bildschirmfoto 2023-08-16 um 16 44 37" src="https://github.com/dot-base/keycloak/assets/38720222/f4b9e890-678b-4250-b65a-6050567e58e2">

### ✔ Goals
Apply the steps above for the following dotbase instances:
- [x] demo.dotbase.org
- [x] one.dev.dotbase.org
- [x] two.dev.dotbase.org
- [x] three.dev.dotbase.org
- [x] matchgraft.dotbase.org
- [x] brustzentrum.dotbase.org
- [x] beta.dotbase.charite.de
- [x] staging.dotbase.charite.de
- [x] dotbase.charite.de
- [x] qre.tbase-fhir.charite.de

### Check if your changes worked 
a) for **dotbase realm** - try to login via medical-dashboard
b) for **patient realm** - try to scan the QR Code and connect dotlink app with patient.

### 🧰 Possible Solution
This is a known issue that has been reported for keycloak 20+ 
- (https://keycloak.discourse.group/t/issue-on-userinfo-endpoint-at-keycloak-20/18461)

To access the userinfo endpoint clients now need an additional scope `openid`
- https://github.com/keycloak/keycloak/pull/14237

In our case for it's **authentication-gateway** client, which requests `/userinfo` and needs to have this scope.

**Comment by Zbozi** [comment]
- MAtchgraft is correclty configured but it does not allow connection qith app and qr code!

**Comment by andreakreichgauer** [comment]
> #### QR-Code error in App
> When trying to connect the app via qr code the app throws following error: 3 _Unbekanter Fehler Es ist ein unbekannter Fehler aufgetreten. Bitte kontaktieren Sie ihre Behandler*innen an der Charité, falls sich dieser Fehler wiederholt._
> 
> Error exist for following instances:
> 
> * matchgraft.dotbase.org
> * one.dev.dotbase.org

Works fine now after releasing 23-4 :)
